name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19df2cd23a24e877d637c777da70ffcbd0bf537c69d8ee7dfb07308ac31b8158"

[versions]
minecraft = "1.19.2"
quilt = "0.29.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "resources"
