name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cac53afe39ab878db7f257064064f9d85eb944a681e7f7c6dca96a8c966175f6"

[versions]
minecraft = "1.19.2"
quilt = "0.29.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "resources"
