name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a3e702513ee28c48b58279cb633b4aabeb863b352fe325a482df9c2995fa546"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "resources"
