name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "741694975639ba81fce9ff2786ad4211affd1af7c110cb6d485bfb398b582d6c"

[versions]
minecraft = "1.19.2"
quilt = "0.29.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "resources"
